import { z } from "zod";

export const memberCreateSchema = z.object({
  id: z.number().optional(),
  mobile_number: z.string().optional(),
  member_id: z.string().min(1, "Member ID is required"),
  first_name: z.string().optional(),
  middle_name: z.string().optional(),
  last_name: z.string().optional(),
  email: z.string().email().optional(),
  gender: z.string().optional(),
  birthday: z.string().datetime().optional(),
  address: z.string().optional(),
  address_line_1: z.string().optional(),
  address_line_2: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zip_code: z.string().optional(),
  membership_status: z.string(),
  profile_photo: z.string().optional().transform((val) => (val === "" ? null : val)), 
  qr_code: z.string().optional(),
});

export const memberUpdateSchema = z.object({
  id: z.number(),
  mobile_number: z.string().optional(),
  member_id: z.string().optional(),
  first_name: z.string().optional(),
  middle_name: z.string().optional(),
  last_name: z.string().optional(),
  email: z.string().email().optional(),
  gender: z.string().optional(),
  birthday: z.string().datetime().optional(),
  address: z.string().optional(),
  address_line_1: z.string().optional(),
  address_line_2: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zip_code: z.string().optional(),
  membership_status: z.string().optional(),
  profile_photo: z.string().optional().transform((val) => (val === "" ? null : val)),
  qr_code: z.string().optional(),
});